'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4918
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/bvc5")>  _
        Public Property WebStoreUrl() As String
            Get
                Return CType(Me("WebStoreUrl"),String)
            End Get
            Set
                Me("WebStoreUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("admin@bvcommerce.com")>  _
        Public Property WebUsename() As String
            Get
                Return CType(Me("WebUsename"),String)
            End Get
            Set
                Me("WebUsename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("password")>  _
        Public Property WebPassword() As String
            Get
                Return CType(Me("WebPassword"),String)
            End Get
            Set
                Me("WebPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastOrderNumber() As String
            Get
                Return CType(Me("LastOrderNumber"),String)
            End Get
            Set
                Me("LastOrderNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SingleOrderNumber() As String
            Get
                Return CType(Me("SingleOrderNumber"),String)
            End Get
            Set
                Me("SingleOrderNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property StartOrderNumber() As String
            Get
                Return CType(Me("StartOrderNumber"),String)
            End Get
            Set
                Me("StartOrderNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property EndOrderNumber() As String
            Get
                Return CType(Me("EndOrderNumber"),String)
            End Get
            Set
                Me("EndOrderNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CompanyFileName() As String
            Get
                Return CType(Me("CompanyFileName"),String)
            End Get
            Set
                Me("CompanyFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseCompanyFile() As Boolean
            Get
                Return CType(Me("UseCompanyFile"),Boolean)
            End Get
            Set
                Me("UseCompanyFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseOrderPrefix() As Boolean
            Get
                Return CType(Me("UseOrderPrefix"),Boolean)
            End Get
            Set
                Me("UseOrderPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC")>  _
        Public Property OrderPrefix() As String
            Get
                Return CType(Me("OrderPrefix"),String)
            End Get
            Set
                Me("OrderPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseUsernamePrefix() As Boolean
            Get
                Return CType(Me("UseUsernamePrefix"),Boolean)
            End Get
            Set
                Me("UseUsernamePrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC")>  _
        Public Property UsernamePrefix() As String
            Get
                Return CType(Me("UsernamePrefix"),String)
            End Get
            Set
                Me("UsernamePrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SendCreditCardInfo() As Boolean
            Get
                Return CType(Me("SendCreditCardInfo"),Boolean)
            End Get
            Set
                Me("SendCreditCardInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseExportDateInsteadOfOrderDate() As Boolean
            Get
                Return CType(Me("UseExportDateInsteadOfOrderDate"),Boolean)
            End Get
            Set
                Me("UseExportDateInsteadOfOrderDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MarkOrdersToBePrinted() As Boolean
            Get
                Return CType(Me("MarkOrdersToBePrinted"),Boolean)
            End Get
            Set
                Me("MarkOrdersToBePrinted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MarkUnpaidOrdersAsPending() As Boolean
            Get
                Return CType(Me("MarkUnpaidOrdersAsPending"),Boolean)
            End Get
            Set
                Me("MarkUnpaidOrdersAsPending") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ExportProductsAsSKU() As Boolean
            Get
                Return CType(Me("ExportProductsAsSKU"),Boolean)
            End Get
            Set
                Me("ExportProductsAsSKU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseQuickBooksItemDescription() As Boolean
            Get
                Return CType(Me("UseQuickBooksItemDescription"),Boolean)
            End Get
            Set
                Me("UseQuickBooksItemDescription") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseInlineTax() As Boolean
            Get
                Return CType(Me("UseInlineTax"),Boolean)
            End Get
            Set
                Me("UseInlineTax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC Shipping")>  _
        Public Property ShippingItemName() As String
            Get
                Return CType(Me("ShippingItemName"),String)
            End Get
            Set
                Me("ShippingItemName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC Handling")>  _
        Public Property HandlingItemName() As String
            Get
                Return CType(Me("HandlingItemName"),String)
            End Get
            Set
                Me("HandlingItemName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BV Tax")>  _
        Public Property InlineTaxItemName() As String
            Get
                Return CType(Me("InlineTaxItemName"),String)
            End Get
            Set
                Me("InlineTaxItemName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Accounts Receivable")>  _
        Public Property InvoiceAccountsReceivableAccount() As String
            Get
                Return CType(Me("InvoiceAccountsReceivableAccount"),String)
            End Get
            Set
                Me("InvoiceAccountsReceivableAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Undeposited Funds")>  _
        Public Property InvoiceDepostAccount() As String
            Get
                Return CType(Me("InvoiceDepostAccount"),String)
            End Get
            Set
                Me("InvoiceDepostAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DepositInvoices() As Boolean
            Get
                Return CType(Me("DepositInvoices"),Boolean)
            End Get
            Set
                Me("DepositInvoices") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DepositSalesReceipts() As Boolean
            Get
                Return CType(Me("DepositSalesReceipts"),Boolean)
            End Get
            Set
                Me("DepositSalesReceipts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Undeposited Funds")>  _
        Public Property SalesReceiptDepositAccount() As String
            Get
                Return CType(Me("SalesReceiptDepositAccount"),String)
            End Get
            Set
                Me("SalesReceiptDepositAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Amex")>  _
        Public Property PaymentAmex() As String
            Get
                Return CType(Me("PaymentAmex"),String)
            End Get
            Set
                Me("PaymentAmex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Diner's Club")>  _
        Public Property PaymentDiners() As String
            Get
                Return CType(Me("PaymentDiners"),String)
            End Get
            Set
                Me("PaymentDiners") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Discover")>  _
        Public Property PaymentDiscover() As String
            Get
                Return CType(Me("PaymentDiscover"),String)
            End Get
            Set
                Me("PaymentDiscover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("JCB")>  _
        Public Property PaymentJCB() As String
            Get
                Return CType(Me("PaymentJCB"),String)
            End Get
            Set
                Me("PaymentJCB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Master Card")>  _
        Public Property PaymentMasterCard() As String
            Get
                Return CType(Me("PaymentMasterCard"),String)
            End Get
            Set
                Me("PaymentMasterCard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Visa")>  _
        Public Property PaymentVisa() As String
            Get
                Return CType(Me("PaymentVisa"),String)
            End Get
            Set
                Me("PaymentVisa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PayPal")>  _
        Public Property PaymentPayPal() As String
            Get
                Return CType(Me("PaymentPayPal"),String)
            End Get
            Set
                Me("PaymentPayPal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telephone")>  _
        Public Property PaymentTelephone() As String
            Get
                Return CType(Me("PaymentTelephone"),String)
            End Get
            Set
                Me("PaymentTelephone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseProductPrefix() As Boolean
            Get
                Return CType(Me("UseProductPrefix"),Boolean)
            End Get
            Set
                Me("UseProductPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC")>  _
        Public Property ProductPrefix() As String
            Get
                Return CType(Me("ProductPrefix"),String)
            End Get
            Set
                Me("ProductPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Other Income")>  _
        Public Property NewProductIncomeAccount() As String
            Get
                Return CType(Me("NewProductIncomeAccount"),String)
            End Get
            Set
                Me("NewProductIncomeAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseShipMethodPrefix() As Boolean
            Get
                Return CType(Me("UseShipMethodPrefix"),Boolean)
            End Get
            Set
                Me("UseShipMethodPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC")>  _
        Public Property ShipMethodPrefix() As String
            Get
                Return CType(Me("ShipMethodPrefix"),String)
            End Get
            Set
                Me("ShipMethodPrefix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Shipping Charge Income")>  _
        Public Property ShippingItemIncomeAccount() As String
            Get
                Return CType(Me("ShippingItemIncomeAccount"),String)
            End Get
            Set
                Me("ShippingItemIncomeAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC Tax Vendor")>  _
        Public Property InlineTaxVendorName() As String
            Get
                Return CType(Me("InlineTaxVendorName"),String)
            End Get
            Set
                Me("InlineTaxVendorName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Shipping Charge Income")>  _
        Public Property HandlineIncomeAccount() As String
            Get
                Return CType(Me("HandlineIncomeAccount"),String)
            End Get
            Set
                Me("HandlineIncomeAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BVC Discount")>  _
        Public Property OrderDiscount() As String
            Get
                Return CType(Me("OrderDiscount"),String)
            End Get
            Set
                Me("OrderDiscount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExportUsersAsName() As Boolean
            Get
                Return CType(Me("ExportUsersAsName"),Boolean)
            End Get
            Set
                Me("ExportUsersAsName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExportReverseUserName() As Boolean
            Get
                Return CType(Me("ExportReverseUserName"),Boolean)
            End Get
            Set
                Me("ExportReverseUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Check")>  _
        Public Property PaymentCheck() As String
            Get
                Return CType(Me("PaymentCheck"),String)
            End Get
            Set
                Me("PaymentCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Email")>  _
        Public Property PaymentEmail() As String
            Get
                Return CType(Me("PaymentEmail"),String)
            End Get
            Set
                Me("PaymentEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PO")>  _
        Public Property PaymentPO() As String
            Get
                Return CType(Me("PaymentPO"),String)
            End Get
            Set
                Me("PaymentPO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cash")>  _
        Public Property PaymentCash() As String
            Get
                Return CType(Me("PaymentCash"),String)
            End Get
            Set
                Me("PaymentCash") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fax")>  _
        Public Property PaymentFax() As String
            Get
                Return CType(Me("PaymentFax"),String)
            End Get
            Set
                Me("PaymentFax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Other")>  _
        Public Property PaymentOther() As String
            Get
                Return CType(Me("PaymentOther"),String)
            End Get
            Set
                Me("PaymentOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BV Connector for QuickBooks")>  _
        Public Property QBApplicationName() As String
            Get
                Return CType(Me("QBApplicationName"),String)
            End Get
            Set
                Me("QBApplicationName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseSubProductNameMatching() As Boolean
            Get
                Return CType(Me("UseSubProductNameMatching"),Boolean)
            End Get
            Set
                Me("UseSubProductNameMatching") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstRun() As Boolean
            Get
                Return CType(Me("FirstRun"),Boolean)
            End Get
            Set
                Me("FirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MarkPaidOrdersToBePrinted() As Boolean
            Get
                Return CType(Me("MarkPaidOrdersToBePrinted"),Boolean)
            End Get
            Set
                Me("MarkPaidOrdersToBePrinted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CreateCustomersAsCompany() As Boolean
            Get
                Return CType(Me("CreateCustomersAsCompany"),Boolean)
            End Get
            Set
                Me("CreateCustomersAsCompany") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseExportDateForShipping() As Boolean
            Get
                Return CType(Me("UseExportDateForShipping"),Boolean)
            End Get
            Set
                Me("UseExportDateForShipping") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/CommerceMain/WebServices3.asmx")>  _
        Public ReadOnly Property OrderExport3_BVC5WebServices_WebServices3() As String
            Get
                Return CType(Me("OrderExport3_BVC5WebServices_WebServices3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImportOrderMode() As Integer
            Get
                Return CType(Me("ImportOrderMode"),Integer)
            End Get
            Set
                Me("ImportOrderMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SendInventoryToWeb() As Boolean
            Get
                Return CType(Me("SendInventoryToWeb"),Boolean)
            End Get
            Set
                Me("SendInventoryToWeb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SendPricesToWeb() As Boolean
            Get
                Return CType(Me("SendPricesToWeb"),Boolean)
            End Get
            Set
                Me("SendPricesToWeb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CreateInventoryItems() As Boolean
            Get
                Return CType(Me("CreateInventoryItems"),Boolean)
            End Get
            Set
                Me("CreateInventoryItems") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cost of Goods Sold")>  _
        Public Property COGAccount() As String
            Get
                Return CType(Me("COGAccount"),String)
            End Get
            Set
                Me("COGAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Inventory Asset")>  _
        Public Property InventoryAssetAccount() As String
            Get
                Return CType(Me("InventoryAssetAccount"),String)
            End Get
            Set
                Me("InventoryAssetAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImportToMode() As Integer
            Get
                Return CType(Me("ImportToMode"),Integer)
            End Get
            Set
                Me("ImportToMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ProductUseTitleOnly() As Boolean
            Get
                Return CType(Me("ProductUseTitleOnly"),Boolean)
            End Get
            Set
                Me("ProductUseTitleOnly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisableTaxes() As Boolean
            Get
                Return CType(Me("DisableTaxes"),Boolean)
            End Get
            Set
                Me("DisableTaxes") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Connector.My.MySettings
            Get
                Return Global.Connector.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
